services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: model_training
    volumes:
      - models_data:/app/models
    command: ["python", "run.py"]
    depends_on: []

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: model_serving
    volumes:
      - models_data:/app/models
    ports:
      - "8000:8000"
    depends_on:
      - train
    command: ["uvicorn", "src.deployment.api:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  models_data:
